'use client';
import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/app/components/header';
import ModelProvider from '@/app/contexts/modal';
import { usePathname } from 'next/navigation';
import ReduxProvider from '@/redux/provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const pathname = usePathname();
	const isHeader = pathname.includes('/signup') || pathname.includes('/Login');
	console.log(pathname);
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ReduxProvider>
					{isHeader ? <></> : <Header />}
					{/* <Header /> */}

					<ModelProvider>{children}</ModelProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
